name: Manually Deploy to Render

on:
  workflow_dispatch:
    branches:
      - "Render"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          render_api_key: ${{secrets.RENDER_API_KEY}}
          render_app_name: ${{secrets.RENDER_APP_NAME}}
          render_email: ${{secrets.RENDER_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
